name:                FSend2
version:             0.1.0.0
github:              "githubuser/FSend2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FSend2#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- text
- bytestring
- filepath
- random
- directory
- aeson
- containers
- time
- scotty
- lzma
- wai
- wai-extra

library:
  source-dirs: src

executables:
  FSend2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unused-imports
    - -XNoImplicitPrelude
    dependencies:
    - FSend2

tests:
  FSend2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FSend2
